apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name | default "app" }}-ip
  namespace: {{ .Values.app.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.app.name | default "app" }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.app.port | default 5000 }}
    # - name: https
    #   protocol: TCP
    #   port: 443
    #   targetPort: {{ .Values.app.port | default 5000 }}